version: '3'

services:
  eszett:
    image: 'kmitrovicitk/eszett:latest'
    build:
      context: .
    container_name: eszett
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/eszett_db
      - SPRING_DATASOURCE_USERNAME=eszett
      - SPRING_DATASOURCE_PASSWORD=eszett01
    ports:
      - "8080:8080"

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=eszett_db
      - POSTGRES_USER=eszett
      - POSTGRES_PASSWORD=eszett01
